all: subset_sum knapsack LCS


subset_sum: subset_sum.cpp
	clang++ -Wall -o subset_sum subset_sum.cpp


knapsack: knapsack.cpp
	clang++ -Wall -o knapsack knapsack.cpp


LCS: LCS.cpp
	clang++ -Wall -o LCS LCS.cpp


clean:
	rm -rf subset_sum knapsack a.out
