all: subset_sum knapsack


subset_sum: subset_sum.cpp
	clang++ -Wall -o subset_sum subset_sum.cpp


knapsack: knapsack.cpp
	clang++ -Wall -o knapsack knapsack.cpp


clean:
	rm -rf subset_sum knapsack a.out
